config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  root to: "home#index"
  mount Sidekiq::Web => '/sidekiq'
  resources :trainers, only: %i[create new show edit update] do
    get 'add_units', on: :member
  end

  devise_for :employees, controllers: {sessions: "employee/sessions"}

  resources :gyms, only: %i[index show new create edit update destroy]
  resources :trainers, only: %i[index create new show edit update] 
  resources :activities, only: %i[index show new create edit update]
  resources :plans, only: %i[index new create show edit update destroy]
  resources :prices, only: %i[new create]
  resources :employees, only: %i[new create show index edit update] do
    get 'change_status', on: :member
  end
  resources :clients, only: %i[show new create edit update index] do
    get 'banishe_client', on: :member, as: 'banishe'
    get 'suspend_client', on: :member, as: 'suspend'
    get 'inactive_client', on: :member, as: 'inactive'
    get 'verify_payments', on: :member
  end

  resources :gym_trainers, only: %i[destroy]
  
  resources :employees, only: %i[new create show]
  resources :gyms, only: %i[] do
    resources :trainers, only: %i[] do 
      resources :gym_trainers, only: %i[create]
    end
  end
  get 'unactives', to: 'employees#unactives', as: 'employees_unactives'

  namespace :api do
    namespace :v1 do
      devise_for :employee, controllers: { sessions: 'api/sessions'}, defaults: { format: :json },
      class_name: 'ApiEmployee',
            skip: [:registrations, :passwords, :confirmations,
                    :unlocks],
            path: '',
      path_names: { sign_in: 'login',
                    sign_out: 'logout' }    
      devise_scope :employee do
        get 'login', to: 'api/sessions#create'
        delete 'logout', to: 'api/sessions#destroy'
      end

      get 'show_all_plans', to: 'plans#show_all'
      resources :plans, only: %i[index show] do
      end
      resources :gyms, only: %i[index show destroy] do
        resources :plans, only: %i[index] 
        resources :activities, only: [:index]
      end
      resources :clients, only: %i[create] do
        get 'consult_cpf/:cpf', to: 'clients#consult_cpf', on: :collection
        post ':cpf', to: 'clients#show', on: :collection
      end
      post 'inactivate_client/:cpf', to: 'clients#inactivate'
    end
  end
  
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :gym
  belongs_to :plan

  validates :name, :cpf, :email, :gym_id, :plan_id, presence: true
  validates :cpf, uniqueness: true

  enum status: { active: 0, inactive: 1, suspended: 2, indebted: 6, banished: 9 }

  def last_payment_status
    Payment.find(cpf).first.status
  end
  
  def profile  
    @profile ||= Profile.find(cpf)
  end
end

app/controllers/api/v1/clients_controller.rb
module Api
  module V1
    class ClientsController < ApiController
      def consult_cpf
        client = Client.find_by(cpf: params[:cpf])
        return render json: { message: 'CPF não encontrado' }, status: :not_found unless client

        render json: client.to_json(only: %i[cpf status]), status: :found
      end

      def create
        client = Client.new(client_params)
        if client.save
          render json: ClientSerializer.new(client).serialized_json, status: :created
        else
          render json: { message: 'Não foi possivel cadastrar esse aluno', errors: client.errors.full_messages }, status: :precondition_failed
        end
      end

      def show
        client = Client.find_by(cpf: params[:cpf])
        return render json: { message: 'Cliente não encontrado' }, status: :not_found unless client

        render json: ClientSerializer.new(client).serialized_json, status: :found
      end

      def inactivate
        client = Client.find_by(cpf: params[:cpf])
        return render json: { message: 'CPF não encontrado' }, status: :not_found unless client

        client.inactive! if client.active?
        render json: ClientStatusSerializer.new(client).serialized_json, status: :accepted
      end

      private

      def client_params
        params.require(:client).permit(:name, :cpf, :email, :gym_id, :plan_id)
      end
    end
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authenticate_employee!
  before_action :find_all, only: %i[create update]
  before_action :find_client_by_id, only: %i[show edit update verify_payments banishe_client suspend_client inactive_client]
  rescue_from ActiveRecord::RecordNotFound, with: :client_not_found
  
  def index
    @clients = Client.all 
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)

    if @client.save
      redirect_to @client, notice: t(:success_create, 
                                     scope: [:notice], models: Client.model_name.human)
    else
      find_all
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @client.update(client_params)
      redirect_to @client, notice: t(:success_update, 
                                     scope: [:notice])
    else
      find_all
      render :edit
    end
  end

  def banishe_client
    BanisheService.new(@client).call

    redirect_to @client, notice: t(:client_banished, 
                                   scope: [:notice])
  end

  def suspend_client
    @client.suspended!
    redirect_to @client, notice: t(:client_suspend, 
                                   scope: [:notice])
  end
  
  def inactive_client
    InactiveService.new(@client).call
    if @client.inactive?
      redirect_to @client, notice: t(:client_inactive, 
                                     scope: [:notice])
    else
      redirect_to @client, alert: t(:fail_inactive, 
                                    scope: %i[alert client])
    end
  end

  def verify_payments
    @client.indebted! if @client.last_payment_status == 'unpaid' && @client.active?
    @client.active! if @client.last_payment_status == 'paid' && @client.indebted?

    redirect_to @client
  end

  private

  def client_params
    params.require(:client).permit(:name, :cpf, :email, :gym_id, :plan_id)
  end

  def find_all
    @gym = Gym.all
    @plan = Plan.all
  end

  def find_client_by_id
    @client ||= Client.find(params[:id])
  end

  def client_not_found
    redirect_to clients_path, alert: t(:not_found, 
                                       scope: %i[alert client])
  end
end

app/views/clients/_form.html.erb
<% if @client.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% @client.errors.full_messages.each do |message| %>
      <li> <%= message %>
    <% end %>
    </ul>
  </div>
<% end %>

<%= bootstrap_form_for @client, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-4"  do |f| %>
  <%= f.text_field :name %> 
  <%= f.text_field :cpf %>
  <%= f.email_field :email %>
  <%= f.collection_select(:gym_id, Gym.all, :id, :name) %>
  <%= f.collection_select(:plan_id, Plan.all, :id, :name) %>
  <%= f.submit %>
<% end %>

app/views/clients/edit.html.erb
<h3> Editar matrícula </h3>

<%= render 'form' %>

app/views/clients/index.html.erb
<h1>Lista de Alunos</h1>

<% @clients.each do |client| %>
  <li><%= link_to client.name, client %></li>
<% end %>

app/views/clients/new.html.erb
<h1> Matrícula </h1>

<%= render 'form' %>

app/views/clients/show.html.erb
<h3>Matrícula</h3>

<p><%= @client.name %></p>
<p><%= @client.cpf %></p>
<p><%= @client.email%></p>
<p><%= @client.gym.name %></p>
<p><%= @client.plan.name %></p>
<p>Status: <%= @client.status %></p>
<% if @client.profile %>
  <p>Endereço: <%= @client.profile.address %></p>
  <p>Data de nascimento: <%= @client.profile.date_of_birth %></p>
  <p>Gênero: <%= @client.profile.gender %></p>
  <p>Contato: <%= @client.profile.contact %></p>
  <p>Apelido: <%= @client.profile.nickname %></p>
  <p>Método de pagamento: <%= @client.profile.payment_method %></p>
<% else%>
  <p> Perfil não encontrado </p>
<% end %>



<%= link_to 'Editar', edit_client_path %>
<%= link_to 'Atualizar status de pagamentos', verify_payments_client_path %>
<%= link_to 'Voltar', clients_path %>
<%= link_to('SUSPENDER ALUNO', suspend_client_path) unless @client.banished? || @client.suspended? %>
<%= link_to('BANIR ALUNO', banishe_client_path, data: { confirm: 'Ação permanente. Tem certeza?' }) unless @client.banished? %>
<%= link_to('DESVINCULAR ALUNO', inactive_client_path, data: { confirm: 'Ação permanente. Tem certeza?' }) if @client.active? %>