config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  root to: "home#index"
  mount Sidekiq::Web => '/sidekiq'
  resources :trainers, only: %i[create new show edit update] do
    get 'add_units', on: :member
  end

  devise_for :employees, controllers: {sessions: "employee/sessions"}

  resources :gyms, only: %i[index show new create edit update destroy]
  resources :trainers, only: %i[index create new show edit update] 
  resources :activities, only: %i[index show new create edit update]
  resources :plans, only: %i[index new create show edit update destroy]
  resources :prices, only: %i[new create]
  resources :employees, only: %i[new create show index edit update] do
    get 'change_status', on: :member
  end
  resources :clients, only: %i[show new create edit update index] do
    get 'banishe_client', on: :member, as: 'banishe'
    get 'suspend_client', on: :member, as: 'suspend'
    get 'inactive_client', on: :member, as: 'inactive'
    get 'verify_payments', on: :member
  end

  resources :gym_trainers, only: %i[destroy]
  
  resources :employees, only: %i[new create show]
  resources :gyms, only: %i[] do
    resources :trainers, only: %i[] do 
      resources :gym_trainers, only: %i[create]
    end
  end
  get 'unactives', to: 'employees#unactives', as: 'employees_unactives'

  namespace :api do
    namespace :v1 do
      devise_for :employee, controllers: { sessions: 'api/sessions'}, defaults: { format: :json },
      class_name: 'ApiEmployee',
            skip: [:registrations, :passwords, :confirmations,
                    :unlocks],
            path: '',
      path_names: { sign_in: 'login',
                    sign_out: 'logout' }    
      devise_scope :employee do
        get 'login', to: 'api/sessions#create'
        delete 'logout', to: 'api/sessions#destroy'
      end

      get 'show_all_plans', to: 'plans#show_all'
      resources :plans, only: %i[index show] do
      end
      resources :gyms, only: %i[index show destroy] do
        resources :plans, only: %i[index] 
        resources :activities, only: [:index]
      end
      resources :clients, only: %i[create] do
        get 'consult_cpf/:cpf', to: 'clients#consult_cpf', on: :collection
        post ':cpf', to: 'clients#show', on: :collection
      end
      post 'inactivate_client/:cpf', to: 'clients#inactivate'
    end
  end
  
end

app/models/plan.rb
class Plan < ApplicationRecord
  validates :name, :minimum_permanence, presence: { message: 'Todos os campos devem ser preenchidos' }
  validates :name, uniqueness: { message: 'O nome deve ser único' }

  has_many :prices
  has_many :gyms, through: :prices
end

app/controllers/api/v1/plans_controller.rb
module Api
  module V1 
    class PlansController < ApiController
      def index
        gym = Gym.find(params[:gym_id])
        plan = gym.plans
        @price = Price.where(plan: plan, gym: gym)
        render json: PriceSerializer.new(@price).serialized_json, status: :ok
      rescue ActiveRecord::RecordNotFound  
        render json: { messages: 'Nenhum plano cadastrado' }, status: :not_found
      end

      def show_all
        plans = Plan.all
        return render json: { menssages: 'Nenhum plano encontrado' }, status: :not_found if plans.empty?

        render json: PlanSerializer.new(plans).serialized_json, status: :ok
      end

      def show 
        plan = Plan.find(params[:id])
        render json: { plan: { name: plan.name, minimum_permanence: plan.minimum_permanence } }
      
      rescue ActiveRecord::RecordNotFound
        render json: { menssages: 'Nenhum plano encontrado' }, status: :not_found
      end
    end
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :authenticate_employee! 
  before_action :authorize_admin
  before_action :find_id, only: %i[show edit update destroy]

  def new 
    @plan = Plan.new 
  end

  def create
    @plan = Plan.new(plan_params)
    logger.info("@plan should be new #{@plan.attributes.inspect}") 
    logger.info("@plan should be valid #{@plan.valid?}") 
    if @plan.save
      logger.info("@plan has been saved successfully.")
      redirect_to @plan, notice: t(:success_create, 
                                   scope: [:notice], models: Plan.model_name.human)
    else
      flash.now[:message] = @plan.errors.full_messages
      render :new
    end
  end

  def show; end

  def index
    @plans = Plan.all
  end

  def edit; end

  def update
    if @plan.update(plan_params)
      redirect_to @plan, notice: t(:success_update, 
                                   scope: [:notice], models: Plan.model_name.human)
    else
      flash.now[:message] = @plan.errors.full_messages
      render :edit
    end
     
  end

  def destroy
    @plan.destroy
    redirect_to plans_path
  end

  private
  
  def plan_params
    params.require(:plan).permit(:name, :minimum_permanence)
  end

  def find_id
    @plan = Plan.find(params[:id])
    logger.info 'mensagem 321123'
    # logger.debug "@plan should have an ID: #{@plan.attributes.inspect}"
  end
end

app/views/plans/edit.html.erb
<div class="text-center font-weight-bold app-space-top-bottom">
  <% @plan.errors.full_messages.each do |message| %>
    <%= message %>
  <%end%>
</div>

<div class="container">
  <div class="row">
    <div class="col">
      <h3>Editando plano:<span class="text-warning font-weight-bold "><%="  #{@plan.name}"%></span></h3>
      </div>
  </div>
  <div class="row">
    <div class="col">

        <%= form_for @plan do |f| %>
          <%= f.label :name %>
          <%= f.text_field :name, class:"form-control app-space-imput-bottom" %>
          <%= f.label :minimum_permanence %>
          <%= f.number_field :minimum_permanence, class:"form-control app-space-input-bottom"%>
          <%= f.submit 'Salvar', class:"btn app-color-button btn-block app-space-button" %>
        <% end %>

    </div>
  </div>

        <%= link_to 'Voltar', plan_path, class:"btn btn-secondary btn-block app-space-button"%>
</div>

app/views/plans/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <h1 class="app-title-spaces ">Gerenciamento de Planos</h1>
    </div>

      <% @plans.each do |plan| %>
        <div class="col-4">
            <div class="shadow p-3 mb-5 bg-white rounded">
              <h3 class="text-center"><%= link_to plan.name, plan %></h3>
              <hr>
              <h5>Resumo:</h5>
              <h6><%= "Permanência mínima: #{plan.minimum_permanence} meses" %></h6>
              <%= link_to "Detalhes", plan, class:"btn btn-secondary btn-block app-space-button" %>
            </div>
        </div>
      <% end %>

    </div>
    <div class="col-4 offset-4">
      <%= link_to 'Voltar', root_path, class:"btn app-color-button btn-block app-space-button"%>
    </div>
  </div>
</div>

app/views/plans/new.html.erb
<div class="text-center font-weight-bold app-space-top-bottom">
  <% @plan.errors.full_messages.each do |message| %>
    <%= message %></li>
  <%end%>
</div>

<div class="container">
  <div class="row">
    <div class="col-5">
      <h1>Cadastro de Planos</h1>
    </div>
  </div>
</div>

<%= bootstrap_form_for @plan, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-4" do |f| %> 
  <%= f.text_field :name %>
  <%= f.number_field :minimum_permanence%>
<div class="container">
  <div class="row">
    <div class="col-2">
      <%= f.submit 'Cadastrar', class:"btn btn-secondary btn-block app-space-button"  %>
      <% end %>
      <%= link_to 'Voltar', root_path, class:"btn btn-secondary btn-block app-space-button"%>

    </div>
  </div>
</div>

app/views/plans/show.html.erb
<div class="text-center font-weight-bold app-space-top-bottom">
  <%= flash[:success] %>
</div>

<div class="container app-container">
  <div class="row">
    <div class="col">
      <h2 class="font-weight-bold text-center text-color"><%= "#{@plan.name}" %></h2>
      <h4>Detalhes:</h4>
      <%= "Permanência mínima: #{@plan.minimum_permanence} meses" %>
    </div>
  </div>
  <div class="row app-space-line-top">
    <div class="col">
      <%= link_to 'Editar', edit_plan_path(@plan), class:"btn btn-secondary btn-block" %>
    </div>
    <div class="col">
      <%= link_to 'Definir preço para unidade',new_price_path, class:"btn btn-secondary btn-block" %>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= link_to 'Deletar Plano', plan_path(@plan), class:"btn btn-secondary btn-block app-space-button", method: :delete %>
      <%= link_to 'Voltar', plans_path, class:"btn app-color-button btn-block app-space-button"%>
    </div>
  </div> 
  
</div>