config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  root to: "home#index"
  mount Sidekiq::Web => '/sidekiq'
  resources :trainers, only: %i[create new show edit update] do
    get 'add_units', on: :member
  end

  devise_for :employees, controllers: {sessions: "employee/sessions"}

  resources :gyms, only: %i[index show new create edit update destroy]
  resources :trainers, only: %i[index create new show edit update] 
  resources :activities, only: %i[index show new create edit update]
  resources :plans, only: %i[index new create show edit update destroy]
  resources :prices, only: %i[new create]
  resources :employees, only: %i[new create show index edit update] do
    get 'change_status', on: :member
  end
  resources :clients, only: %i[show new create edit update index] do
    get 'banishe_client', on: :member, as: 'banishe'
    get 'suspend_client', on: :member, as: 'suspend'
    get 'inactive_client', on: :member, as: 'inactive'
    get 'verify_payments', on: :member
  end

  resources :gym_trainers, only: %i[destroy]
  
  resources :employees, only: %i[new create show]
  resources :gyms, only: %i[] do
    resources :trainers, only: %i[] do 
      resources :gym_trainers, only: %i[create]
    end
  end
  get 'unactives', to: 'employees#unactives', as: 'employees_unactives'

  namespace :api do
    namespace :v1 do
      devise_for :employee, controllers: { sessions: 'api/sessions'}, defaults: { format: :json },
      class_name: 'ApiEmployee',
            skip: [:registrations, :passwords, :confirmations,
                    :unlocks],
            path: '',
      path_names: { sign_in: 'login',
                    sign_out: 'logout' }    
      devise_scope :employee do
        get 'login', to: 'api/sessions#create'
        delete 'logout', to: 'api/sessions#destroy'
      end

      get 'show_all_plans', to: 'plans#show_all'
      resources :plans, only: %i[index show] do
      end
      resources :gyms, only: %i[index show destroy] do
        resources :plans, only: %i[index] 
        resources :activities, only: [:index]
      end
      resources :clients, only: %i[create] do
        get 'consult_cpf/:cpf', to: 'clients#consult_cpf', on: :collection
        post ':cpf', to: 'clients#show', on: :collection
      end
      post 'inactivate_client/:cpf', to: 'clients#inactivate'
    end
  end
  
end

app/models/trainer.rb
class Trainer < ApplicationRecord
  has_many :gym_trainers
  has_many :gyms, through: :gym_trainers

  has_many :activities

  enum status: { available: 0, unavailable: 10 }

  validates :name, :cpf, presence: true
  validates :cpf, uniqueness: true

  def translate_status
    I18n.t "activerecord.attributes.trainer.status.#{status}"
  end

  def gym?(gym)
    gyms.include?(gym)
  end

  def gym_trainer(gym)
    gym_trainers.find_by(gym: gym)
  end
end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController 
  before_action :authenticate_employee!, only: %i[new create edit update show]
  before_action :params_find, only: %i[show edit update add_units]
  before_action :authorize_admin, only: [:add_units]

  def new
    @trainer = Trainer.new
  end

  def create
    @trainer = Trainer.new(set_trainer)  
    if @trainer.save       
      @gym_trainer = GymTrainer.create(trainer: @trainer, gym: current_employee.gym) unless current_employee.admin
      redirect_to @trainer, notice: t(:success_create, 
                                      scope: [:notice], models: Trainer.model_name.human)
    else
      flash.now[:message] = @trainer.errors.full_messages.first
      render :new
    end    
  end

  def show;  end

  def edit;  end

  def update
    if @trainer.update(set_trainer)
      flash[:message] = t(:success_update, scope: [:notice])
      redirect_to @trainer
    else
      flash.now[:message] = @trainer.errors.full_messages
      render :edit
    end
  end

  def index
    @trainers = Trainer.all
  end

  def add_units
    @gyms = Gym.all
    @gym_trainer = GymTrainer.new
  end

  private 

  def set_trainer
    params.require(:trainer).permit(:name, :cpf, :email, :status)
  end

  def params_find
    @trainer = Trainer.find(params[:id])
  end
end

app/views/trainers/_form.html.erb
<%= bootstrap_form_for @trainer, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-4" do |f|%>
  <%= f.text_field :name %>
  <%= f.text_field :cpf %>
  <%= f.text_field :email %>
  <%= f.submit 'Cadastrar'%>
<% end %>

app/views/trainers/add_units.html.erb
<div class="text-center">

  <div class="row" >

    <%@gyms.each do |gym|%>
        <div id="<%=gym.id%>"class="col-4">

            <h3 ><%= gym.name %></h3>
            <%if @trainer.gym?(gym) %>
              <h3><%= link_to "Desvincular", gym_trainer_path(@trainer.gym_trainer(gym).id), method: :delete, style: 'color:red;' %></h3>
            <% else %>
              <h3><%= link_to "Vincular", gym_trainer_gym_trainers_path(gym, @trainer), method: :post %></h3>
            <% end %>

          </br>
        </div>
    <% end %>

  </div>

  <h3><%= link_to "Voltar", @trainer%></h3>
</div>

app/views/trainers/edit.html.erb
<%= flash[:message] %>
<%= form_for @trainer do |f|%>
  <%= f.label :name, 'Nome'%>
  <%= f.text_field :name %>
  <%= f.label :cpf, 'CPF'%>
  <%= f.text_field :cpf %>
<%#= collection_select(:user, :id, @users, :id, :name) %>
  <%= f.label :status, 'Status' %>
  <%= f.select(:status, [['Disponível', "available"],['Indisponível', 'unavailable']]) %>
  
  
  <%= f.submit 'Editar'%>
<% end %>

app/views/trainers/index.html.erb
<div class="text-center">
  <h1>Lista de Professores</h1>

  <div class="row">
    <% @trainers.each do |trainer| %>
      <div class="col-3">

          <h2><%= link_to trainer.name, trainer %></h2>
          <p>CPF: <%= trainer.cpf %></p>
          <p>Status: <%= trainer.translate_status %></p>

      </div>
    <%end%>
  </div>
</div>

app/views/trainers/new.html.erb
<h1>Cadastro de Professor</h1>
<%= flash[:message]%>
<%= render "form" %>

app/views/trainers/show.html.erb
<center>

<div style="font-size:25px">
<h1><%= @trainer.name %></h1>
<p><b>CPF:</b> <%= @trainer.cpf %></p>

<p><b> Status: </b><%= @trainer.translate_status%></p>

<p><b>Academias que faz parte</b></p>

<ul>
<% @trainer.gym_trainers.each do |gym_trainer|  %>
  <li><%= gym_trainer.gym.name%></li>

<% end %>
</ul>

<p><%= link_to "Editar", edit_trainer_path(@trainer)%></p>
<% if current_employee.admin? %>
  <%= link_to "Adicionar mais unidades", add_units_trainer_path(@trainer.id) %>
<% end %>
<p><%= link_to "Voltar", trainers_path%></p>
</div>
</center>