config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  root to: "home#index"
  mount Sidekiq::Web => '/sidekiq'
  resources :trainers, only: %i[create new show edit update] do
    get 'add_units', on: :member
  end

  devise_for :employees, controllers: {sessions: "employee/sessions"}

  resources :gyms, only: %i[index show new create edit update destroy]
  resources :trainers, only: %i[index create new show edit update] 
  resources :activities, only: %i[index show new create edit update]
  resources :plans, only: %i[index new create show edit update destroy]
  resources :prices, only: %i[new create]
  resources :employees, only: %i[new create show index edit update] do
    get 'change_status', on: :member
  end
  resources :clients, only: %i[show new create edit update index] do
    get 'banishe_client', on: :member, as: 'banishe'
    get 'suspend_client', on: :member, as: 'suspend'
    get 'inactive_client', on: :member, as: 'inactive'
    get 'verify_payments', on: :member
  end

  resources :gym_trainers, only: %i[destroy]
  
  resources :employees, only: %i[new create show]
  resources :gyms, only: %i[] do
    resources :trainers, only: %i[] do 
      resources :gym_trainers, only: %i[create]
    end
  end
  get 'unactives', to: 'employees#unactives', as: 'employees_unactives'

  namespace :api do
    namespace :v1 do
      devise_for :employee, controllers: { sessions: 'api/sessions'}, defaults: { format: :json },
      class_name: 'ApiEmployee',
            skip: [:registrations, :passwords, :confirmations,
                    :unlocks],
            path: '',
      path_names: { sign_in: 'login',
                    sign_out: 'logout' }    
      devise_scope :employee do
        get 'login', to: 'api/sessions#create'
        delete 'logout', to: 'api/sessions#destroy'
      end

      get 'show_all_plans', to: 'plans#show_all'
      resources :plans, only: %i[index show] do
      end
      resources :gyms, only: %i[index show destroy] do
        resources :plans, only: %i[index] 
        resources :activities, only: [:index]
      end
      resources :clients, only: %i[create] do
        get 'consult_cpf/:cpf', to: 'clients#consult_cpf', on: :collection
        post ':cpf', to: 'clients#show', on: :collection
      end
      post 'inactivate_client/:cpf', to: 'clients#inactivate'
    end
  end
  
end

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small class="footer-content">
      Projeto Final - Imersão Web - TreinaDev 2019 |
      <%= link_to 'GitHub Repo', 'https://github.com/campuscode-alumni/esperto_fit_academy', target: :_blank %>
    </small>
  </footer>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <%= link_to image_tag('logo espertofit Color'), root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if employee_signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Cadastros
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'Cadastrar Academia', new_gym_path, class:"dropdown-item" %>
            <%= link_to 'Cadastrar Aula', new_activity_path, class:"dropdown-item" %>
            <%= link_to 'Cadastrar Professor', new_trainer_path, class:"dropdown-item" %>
            <%= link_to 'Cadastrar Aluno', new_client_path, class:"dropdown-item" %>
            <% if current_employee.admin? %>
              <div class="dropdown-divider"></div>
              <%= link_to 'Cadastrar Funcionário', new_employee_path, class:"dropdown-item" %>
              <%= link_to 'Cadastrar Plano', new_plan_path, class:"dropdown-item" %>
              <%= link_to 'Cadastrar Preços', new_price_path, class:"dropdown-item" %>
            <% end %>
          </div>
        </li>

        <% if current_employee.admin? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Listas
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'Lista de Aulas', activities_path, class:"dropdown-item" %>
              <%= link_to 'Lista de Alunos', clients_path, class:"dropdown-item" %>
              <%= link_to 'Lista de Funcionários Ativos', employees_path, class:"dropdown-item" %>
              <%= link_to 'Lista de Funcionários Inativos', employees_unactives_path, class:"dropdown-item" %>
              <%= link_to 'Lista de Academias', gyms_path, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Listas
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to 'Lista de Aulas', activities_path, class:"dropdown-item" %>
              <%= link_to 'Lista de Alunos', clients_path, class:"dropdown-item" %>
              <%= link_to 'Lista de Academias', gyms_path, class: "dropdown-item" %>
            </div>
          </li>
        <% end %>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Gerenciar
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'Gerenciar Professores', trainers_path, class:"dropdown-item" %>
            <% if current_employee.admin? %>
              <%= link_to 'Gerenciar Planos', plans_path, class:"dropdown-item" %>
            <% end %>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to 'Meu Perfil', employee_path(current_employee), class: "nav-link"  %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sair', destroy_employee_session_path, method: :delete, class: "nav-link"  %>
        </li>
        <li class="nav-link text-white">
          <%= current_employee.name %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Entrar', new_employee_session_path, class: "nav-link"  %>
        </li>

      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EspertoFitAcademy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= flash[:message]%>

    <%= render 'layouts/navbar' %>


    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>